// multilang-game-canvas-arcade.test.ts — every multilang engine's
// game.canvas-arcade.v1 compute core must produce the EXACT oracle of the
// JS model (benchmarks/v2/game-family/engine.js arcade() on the frozen
// 14,424-byte fixture generated by fixtures.js from seed 0x6d2b79f5 —
// 3,600 frames, 169,501 entity updates / 169,501 collision tests /
// 180,301 draw commands / 91 audio events, plus finalStateDigest 87695460,
// drawCommandStreamDigest f3a03070, audioEventStreamDigest 8b4cb497, and
// semanticDigest 585a29e5).
import { assert } from "./assert.ts";

const rootDir = new URL("../", import.meta.url).pathname.replace(/\/$/, "");
const ARTIFACTS = `${rootDir}/public/artifacts/multilang-wasm-benchmark`;
const FIXTURE_PATH =
  `${rootDir}/public/artifacts/game-v2-controlled-family/game-canvas-arcade-v1.bin`;
const FIXTURE_OFFSET = 65536;
const RES_OFFSET = 131072;

// Pinned counters + digests from runGameJavaScript("game.canvas-arcade.v1")
// and tests/v2/game-family.test.ts.
const ORACLE = Object.freeze({
  semantic: 0x585a29e5,
  state: 0x87695460,
  draw: 0xf3a03070,
  audio: 0x8b4cb497,
  entityUpdates: 169501,
  collisionTests: 169501,
  drawCommands: 180301,
  audioEvents: 91,
});

async function readFixture(): Promise<Uint8Array> {
  return await Deno.readFile(FIXTURE_PATH);
}

async function loadWasm(file: string, imports: WebAssembly.Imports = {}) {
  const bytes = await Deno.readFile(`${ARTIFACTS}/${file}`);
  const { instance } = await WebAssembly.instantiate(bytes, imports);
  return instance;
}

function runKernel(instance: WebAssembly.Instance, fixture: Uint8Array) {
  const exports = instance.exports as Record<string, unknown>;
  const mem = new Uint8Array((exports.memory as WebAssembly.Memory).buffer);
  mem.set(fixture, FIXTURE_OFFSET);
  const ret = Number((exports.arcade_trace as (n: number) => number)(fixture.byteLength));
  const view = new Uint32Array((exports.memory as WebAssembly.Memory).buffer);
  const base = RES_OFFSET / 4;
  return {
    ret,
    semantic: view[base] >>> 0,
    state: view[base + 1] >>> 0,
    draw: view[base + 2] >>> 0,
    audio: view[base + 3] >>> 0,
    entityUpdates: view[base + 4],
    collisionTests: view[base + 5],
    drawCommands: view[base + 6],
    audioEvents: view[base + 7],
  };
}

function assertOracle(label: string, r: ReturnType<typeof runKernel>) {
  assert(r.ret === 0, `${label} run returned non-zero status ${r.ret}`);
  assert(
    r.semantic === ORACLE.semantic,
    `${label} semanticDigest ${r.semantic.toString(16)} != ${ORACLE.semantic.toString(16)}`,
  );
  assert(
    r.state === ORACLE.state,
    `${label} finalStateDigest ${r.state.toString(16)} != ${ORACLE.state.toString(16)}`,
  );
  assert(
    r.draw === ORACLE.draw,
    `${label} drawCommandStreamDigest ${r.draw.toString(16)} != ${ORACLE.draw.toString(16)}`,
  );
  assert(
    r.audio === ORACLE.audio,
    `${label} audioEventStreamDigest ${r.audio.toString(16)} != ${ORACLE.audio.toString(16)}`,
  );
  assert(
    r.entityUpdates === ORACLE.entityUpdates,
    `${label} entityUpdates ${r.entityUpdates} != ${ORACLE.entityUpdates}`,
  );
  assert(
    r.collisionTests === ORACLE.collisionTests,
    `${label} collisionTests ${r.collisionTests} != ${ORACLE.collisionTests}`,
  );
  assert(
    r.drawCommands === ORACLE.drawCommands,
    `${label} drawCommands ${r.drawCommands} != ${ORACLE.drawCommands}`,
  );
  assert(
    r.audioEvents === ORACLE.audioEvents,
    `${label} audioEvents ${r.audioEvents} != ${ORACLE.audioEvents}`,
  );
}

Deno.test("multilang game-canvas-arcade: JS engine runGameJavaScript matches the oracle exactly", async () => {
  const { runGameJavaScript } = await import(
    `${rootDir}/benchmarks/v2/game-family/engine.js`
  );
  const result = runGameJavaScript("game.canvas-arcade.v1");
  assert(
    result.oracle.finalStateDigest === ORACLE.state.toString(16).padStart(8, "0"),
    `JS finalStateDigest ${result.oracle.finalStateDigest}`,
  );
  assert(
    result.oracle.drawCommandStreamDigest === ORACLE.draw.toString(16).padStart(8, "0"),
    `JS drawCommandStreamDigest ${result.oracle.drawCommandStreamDigest}`,
  );
  assert(
    result.oracle.audioEventStreamDigest === ORACLE.audio.toString(16).padStart(8, "0"),
    `JS audioEventStreamDigest ${result.oracle.audioEventStreamDigest}`,
  );
  assert(
    result.semanticDigest === ORACLE.semantic.toString(16).padStart(8, "0"),
    `JS semanticDigest ${result.semanticDigest}`,
  );
  assert(
    result.counters.entityUpdates === ORACLE.entityUpdates,
    `JS entityUpdates ${result.counters.entityUpdates}`,
  );
  assert(
    result.counters.collisionTests === ORACLE.collisionTests,
    `JS collisionTests ${result.counters.collisionTests}`,
  );
  assert(
    result.counters.drawCommands === ORACLE.drawCommands,
    `JS drawCommands ${result.counters.drawCommands}`,
  );
  assert(
    result.counters.audioEvents === ORACLE.audioEvents,
    `JS audioEvents ${result.counters.audioEvents}`,
  );
});

Deno.test("multilang game-canvas-arcade: C kernel matches the JS oracle exactly", async () => {
  const fixture = await readFixture();
  const r = runKernel(await loadWasm("arcade_kernel_c.wasm"), fixture);
  assertOracle("C", r);
});

Deno.test("multilang game-canvas-arcade: C++ kernel matches the JS oracle exactly", async () => {
  const fixture = await readFixture();
  const r = runKernel(await loadWasm("arcade_kernel_cpp.wasm"), fixture);
  assertOracle("C++", r);
});

Deno.test("multilang game-canvas-arcade: Rust kernel matches the JS oracle exactly", async () => {
  const fixture = await readFixture();
  const r = runKernel(await loadWasm("arcade_kernel_rs.wasm"), fixture);
  assertOracle("Rust", r);
});

Deno.test("multilang game-canvas-arcade: AssemblyScript kernel matches the JS oracle exactly", async () => {
  const fixture = await readFixture();
  const r = runKernel(
    await loadWasm("arcade_kernel_asc.wasm", { env: { abort: () => {} } }),
    fixture,
  );
  assertOracle("AS", r);
});
