// multilang-game-pathfinding.test.ts — every multilang engine's
// game.canvas-entity-pathfinding.v1 compute core must produce the EXACT
// oracle of the JS model (benchmarks/v2/game-family/engine.js pathfinding()
// on the frozen 106,552-byte fixture generated by fixtures.js from seed
// 0x8f4c21a7 — 128 A* paths + 1,800-frame ECS on a 256×256 grid;
// pathNodeSequenceDigest 55c75f61, tieBreakDigest 8108145d,
// ecsCheckpointDigest c497aa94, animationCommandStreamDigest 569ffa98,
// drawCommandStreamDigest 992a9d1d, audioEventStreamDigest d1fcc811;
// counters: 7,372,800 systemUpdates / 974,592 pathNodesExpanded /
// 2,213,135 frontierOperations / 7,372,800 drawCommands / 1 audioEvent;
// semantic fe0377bf).
import { assert } from "./assert.ts";

const rootDir = new URL("../", import.meta.url).pathname.replace(/\/$/, "");
const ARTIFACTS = `${rootDir}/public/artifacts/multilang-wasm-benchmark`;
const FIXTURE_PATH =
  `${rootDir}/public/artifacts/game-v2-controlled-family/game-canvas-entity-pathfinding-v1.bin`;
const FIXTURE_OFFSET = 3145728;
const RES_OFFSET = 3276800;

const ORACLE = Object.freeze({
  semantic: 0xfe0377bf,
  path: 0x55c75f61,
  tie: 0x8108145d,
  ecs: 0xc497aa94,
  animation: 0x569ffa98,
  draw: 0x992a9d1d,
  audio: 0xd1fcc811,
  systemUpdates: 7372800,
  pathNodesExpanded: 974592,
  frontierOperations: 2213135,
  drawCommands: 7372800,
  audioEvents: 1,
});

async function readFixture(): Promise<Uint8Array> {
  return await Deno.readFile(FIXTURE_PATH);
}

async function loadWasm(file: string, imports: WebAssembly.Imports = {}) {
  const bytes = await Deno.readFile(`${ARTIFACTS}/${file}`);
  const { instance } = await WebAssembly.instantiate(bytes, imports);
  return instance;
}

function runKernel(instance: WebAssembly.Instance, fixture: Uint8Array) {
  const exports = instance.exports as Record<string, unknown>;
  const mem = new Uint8Array((exports.memory as WebAssembly.Memory).buffer);
  mem.set(fixture, FIXTURE_OFFSET);
  const ret = Number(
    (exports.pathfinding_trace as (n: number) => number)(fixture.byteLength),
  );
  const view = new Uint32Array((exports.memory as WebAssembly.Memory).buffer);
  const base = RES_OFFSET / 4;
  return {
    ret,
    semantic: view[base] >>> 0,
    path: view[base + 1] >>> 0,
    tie: view[base + 2] >>> 0,
    ecs: view[base + 3] >>> 0,
    animation: view[base + 4] >>> 0,
    draw: view[base + 5] >>> 0,
    audio: view[base + 6] >>> 0,
    systemUpdates: view[base + 7],
    pathNodesExpanded: view[base + 8],
    frontierOperations: view[base + 9],
    drawCommands: view[base + 10],
    audioEvents: view[base + 11],
  };
}

function assertOracle(label: string, r: ReturnType<typeof runKernel>) {
  assert(r.ret === 0, `${label} run returned non-zero status ${r.ret}`);
  assert(
    r.semantic === ORACLE.semantic,
    `${label} semanticDigest ${r.semantic.toString(16)} != ${ORACLE.semantic.toString(16)}`,
  );
  assert(
    r.path === ORACLE.path,
    `${label} pathNodeSequenceDigest ${r.path.toString(16)} != ${ORACLE.path.toString(16)}`,
  );
  assert(
    r.tie === ORACLE.tie,
    `${label} tieBreakDigest ${r.tie.toString(16)} != ${ORACLE.tie.toString(16)}`,
  );
  assert(
    r.ecs === ORACLE.ecs,
    `${label} ecsCheckpointDigest ${r.ecs.toString(16)} != ${ORACLE.ecs.toString(16)}`,
  );
  assert(
    r.animation === ORACLE.animation,
    `${label} animationCommandStreamDigest ${r.animation.toString(16)} != ${
      ORACLE.animation.toString(16)
    }`,
  );
  assert(
    r.draw === ORACLE.draw,
    `${label} drawCommandStreamDigest ${r.draw.toString(16)} != ${ORACLE.draw.toString(16)}`,
  );
  assert(
    r.audio === ORACLE.audio,
    `${label} audioEventStreamDigest ${r.audio.toString(16)} != ${ORACLE.audio.toString(16)}`,
  );
  assert(
    r.systemUpdates === ORACLE.systemUpdates,
    `${label} systemUpdates ${r.systemUpdates} != ${ORACLE.systemUpdates}`,
  );
  assert(
    r.pathNodesExpanded === ORACLE.pathNodesExpanded,
    `${label} pathNodesExpanded ${r.pathNodesExpanded} != ${ORACLE.pathNodesExpanded}`,
  );
  assert(
    r.frontierOperations === ORACLE.frontierOperations,
    `${label} frontierOperations ${r.frontierOperations} != ${ORACLE.frontierOperations}`,
  );
  assert(
    r.drawCommands === ORACLE.drawCommands,
    `${label} drawCommands ${r.drawCommands} != ${ORACLE.drawCommands}`,
  );
  assert(
    r.audioEvents === ORACLE.audioEvents,
    `${label} audioEvents ${r.audioEvents} != ${ORACLE.audioEvents}`,
  );
}

Deno.test("multilang game-pathfinding: JS engine runGameJavaScript matches the oracle exactly", async () => {
  const { runGameJavaScript } = await import(
    `${rootDir}/benchmarks/v2/game-family/engine.js`
  );
  const result = runGameJavaScript("game.canvas-entity-pathfinding.v1");
  assert(
    result.oracle.pathNodeSequenceDigest === ORACLE.path.toString(16).padStart(8, "0"),
    `JS pathNodeSequenceDigest ${result.oracle.pathNodeSequenceDigest}`,
  );
  assert(
    result.oracle.tieBreakDigest === ORACLE.tie.toString(16).padStart(8, "0"),
    `JS tieBreakDigest ${result.oracle.tieBreakDigest}`,
  );
  assert(
    result.oracle.ecsCheckpointDigest === ORACLE.ecs.toString(16).padStart(8, "0"),
    `JS ecsCheckpointDigest ${result.oracle.ecsCheckpointDigest}`,
  );
  assert(
    result.oracle.animationCommandStreamDigest ===
      ORACLE.animation.toString(16).padStart(8, "0"),
    `JS animationCommandStreamDigest ${result.oracle.animationCommandStreamDigest}`,
  );
  assert(
    result.oracle.drawCommandStreamDigest === ORACLE.draw.toString(16).padStart(8, "0"),
    `JS drawCommandStreamDigest ${result.oracle.drawCommandStreamDigest}`,
  );
  assert(
    result.oracle.audioEventStreamDigest === ORACLE.audio.toString(16).padStart(8, "0"),
    `JS audioEventStreamDigest ${result.oracle.audioEventStreamDigest}`,
  );
  assert(
    result.semanticDigest === ORACLE.semantic.toString(16).padStart(8, "0"),
    `JS semanticDigest ${result.semanticDigest}`,
  );
  assert(
    result.counters.systemUpdates === ORACLE.systemUpdates,
    `JS systemUpdates ${result.counters.systemUpdates}`,
  );
  assert(
    result.counters.pathNodesExpanded === ORACLE.pathNodesExpanded,
    `JS pathNodesExpanded ${result.counters.pathNodesExpanded}`,
  );
  assert(
    result.counters.frontierOperations === ORACLE.frontierOperations,
    `JS frontierOperations ${result.counters.frontierOperations}`,
  );
  assert(
    result.counters.drawCommands === ORACLE.drawCommands,
    `JS drawCommands ${result.counters.drawCommands}`,
  );
  assert(
    result.counters.audioEvents === ORACLE.audioEvents,
    `JS audioEvents ${result.counters.audioEvents}`,
  );
});

Deno.test("multilang game-pathfinding: C kernel matches the JS oracle exactly", async () => {
  const fixture = await readFixture();
  const r = runKernel(await loadWasm("pathfinding_kernel_c.wasm"), fixture);
  assertOracle("C", r);
});

Deno.test("multilang game-pathfinding: C++ kernel matches the JS oracle exactly", async () => {
  const fixture = await readFixture();
  const r = runKernel(await loadWasm("pathfinding_kernel_cpp.wasm"), fixture);
  assertOracle("C++", r);
});

Deno.test("multilang game-pathfinding: Rust kernel matches the JS oracle exactly", async () => {
  const fixture = await readFixture();
  const r = runKernel(await loadWasm("pathfinding_kernel_rs.wasm"), fixture);
  assertOracle("Rust", r);
});

Deno.test("multilang game-pathfinding: AssemblyScript kernel matches the JS oracle exactly", async () => {
  const fixture = await readFixture();
  const r = runKernel(
    await loadWasm("pathfinding_kernel_asc.wasm", { env: { abort: () => {} } }),
    fixture,
  );
  assertOracle("AS", r);
});
