// multilang-game-tactics-grid.test.ts — every multilang engine's
// game.dom-tactics-grid.v1 compute core must produce the EXACT oracle of
// the JS model (benchmarks/v2/game-family/engine.js tactics() on the frozen
// 7,064-byte fixture generated by fixtures.js from seed 0x7c3a19e5 —
// 60 turns of 4 actions each on a 64×64 map with 128 units; finalUnitDigest
// adaea4e5, finalOccupancyDigest 8d730f69, finalInitiativeDigest 67cf2fa8,
// finalObjectiveDigest dc971318, canonicalDomDigest ea6127a1,
// focusStateDigest 103c75c2, accessibilityStateDigest e819fe54;
// counters: 60 turns / 95,614 pathNodesExpanded / 450 lineOfSightTests /
// 81 stateUpdates / 423 domMutations; semantic 5081f3e4).
import { assert } from "./assert.ts";

const rootDir = new URL("../", import.meta.url).pathname.replace(/\/$/, "");
const ARTIFACTS = `${rootDir}/public/artifacts/multilang-wasm-benchmark`;
const FIXTURE_PATH =
  `${rootDir}/public/artifacts/game-v2-controlled-family/game-dom-tactics-grid-v1.bin`;
const FIXTURE_OFFSET = 3145728;
const RES_OFFSET = 3276800;

const ORACLE = Object.freeze({
  semantic: 0x5081f3e4,
  unit: 0xadaea4e5,
  occupancy: 0x8d730f69,
  initiative: 0x67cf2fa8,
  objective: 0xdc971318,
  dom: 0xea6127a1,
  focus: 0x103c75c2,
  accessibility: 0xe819fe54,
  turns: 60,
  pathNodesExpanded: 95614,
  lineOfSightTests: 450,
  stateUpdates: 81,
  domMutations: 423,
});

async function readFixture(): Promise<Uint8Array> {
  return await Deno.readFile(FIXTURE_PATH);
}

async function loadWasm(file: string, imports: WebAssembly.Imports = {}) {
  const bytes = await Deno.readFile(`${ARTIFACTS}/${file}`);
  const { instance } = await WebAssembly.instantiate(bytes, imports);
  return instance;
}

function runKernel(instance: WebAssembly.Instance, fixture: Uint8Array) {
  const exports = instance.exports as Record<string, unknown>;
  const mem = new Uint8Array((exports.memory as WebAssembly.Memory).buffer);
  mem.set(fixture, FIXTURE_OFFSET);
  const ret = Number(
    (exports.tactics_trace as (n: number) => number)(fixture.byteLength),
  );
  const view = new Uint32Array((exports.memory as WebAssembly.Memory).buffer);
  const base = RES_OFFSET / 4;
  return {
    ret,
    semantic: view[base] >>> 0,
    unit: view[base + 1] >>> 0,
    occupancy: view[base + 2] >>> 0,
    initiative: view[base + 3] >>> 0,
    objective: view[base + 4] >>> 0,
    dom: view[base + 5] >>> 0,
    focus: view[base + 6] >>> 0,
    accessibility: view[base + 7] >>> 0,
    turns: view[base + 8],
    pathNodesExpanded: view[base + 9],
    lineOfSightTests: view[base + 10],
    stateUpdates: view[base + 11],
    domMutations: view[base + 12],
  };
}

function assertOracle(label: string, r: ReturnType<typeof runKernel>) {
  assert(r.ret === 0, `${label} run returned non-zero status ${r.ret}`);
  assert(
    r.semantic === ORACLE.semantic,
    `${label} semanticDigest ${r.semantic.toString(16)} != ${ORACLE.semantic.toString(16)}`,
  );
  assert(
    r.unit === ORACLE.unit,
    `${label} finalUnitDigest ${r.unit.toString(16)} != ${ORACLE.unit.toString(16)}`,
  );
  assert(
    r.occupancy === ORACLE.occupancy,
    `${label} finalOccupancyDigest ${r.occupancy.toString(16)} != ${ORACLE.occupancy.toString(16)}`,
  );
  assert(
    r.initiative === ORACLE.initiative,
    `${label} finalInitiativeDigest ${r.initiative.toString(16)} != ${
      ORACLE.initiative.toString(16)
    }`,
  );
  assert(
    r.objective === ORACLE.objective,
    `${label} finalObjectiveDigest ${r.objective.toString(16)} != ${ORACLE.objective.toString(16)}`,
  );
  assert(
    r.dom === ORACLE.dom,
    `${label} canonicalDomDigest ${r.dom.toString(16)} != ${ORACLE.dom.toString(16)}`,
  );
  assert(
    r.focus === ORACLE.focus,
    `${label} focusStateDigest ${r.focus.toString(16)} != ${ORACLE.focus.toString(16)}`,
  );
  assert(
    r.accessibility === ORACLE.accessibility,
    `${label} accessibilityStateDigest ${r.accessibility.toString(16)} != ${
      ORACLE.accessibility.toString(16)
    }`,
  );
  assert(r.turns === ORACLE.turns, `${label} turns ${r.turns} != ${ORACLE.turns}`);
  assert(
    r.pathNodesExpanded === ORACLE.pathNodesExpanded,
    `${label} pathNodesExpanded ${r.pathNodesExpanded} != ${ORACLE.pathNodesExpanded}`,
  );
  assert(
    r.lineOfSightTests === ORACLE.lineOfSightTests,
    `${label} lineOfSightTests ${r.lineOfSightTests} != ${ORACLE.lineOfSightTests}`,
  );
  assert(
    r.stateUpdates === ORACLE.stateUpdates,
    `${label} stateUpdates ${r.stateUpdates} != ${ORACLE.stateUpdates}`,
  );
  assert(
    r.domMutations === ORACLE.domMutations,
    `${label} domMutations ${r.domMutations} != ${ORACLE.domMutations}`,
  );
}

Deno.test("multilang game-tactics-grid: JS engine runGameJavaScript matches the oracle exactly", async () => {
  const { runGameJavaScript } = await import(
    `${rootDir}/benchmarks/v2/game-family/engine.js`
  );
  const result = runGameJavaScript("game.dom-tactics-grid.v1");
  assert(
    result.oracle.finalUnitDigest === ORACLE.unit.toString(16).padStart(8, "0"),
    `JS finalUnitDigest ${result.oracle.finalUnitDigest}`,
  );
  assert(
    result.oracle.finalOccupancyDigest === ORACLE.occupancy.toString(16).padStart(8, "0"),
    `JS finalOccupancyDigest ${result.oracle.finalOccupancyDigest}`,
  );
  assert(
    result.oracle.finalInitiativeDigest ===
      ORACLE.initiative.toString(16).padStart(8, "0"),
    `JS finalInitiativeDigest ${result.oracle.finalInitiativeDigest}`,
  );
  assert(
    result.oracle.finalObjectiveDigest === ORACLE.objective.toString(16).padStart(8, "0"),
    `JS finalObjectiveDigest ${result.oracle.finalObjectiveDigest}`,
  );
  assert(
    result.oracle.canonicalDomDigest === ORACLE.dom.toString(16).padStart(8, "0"),
    `JS canonicalDomDigest ${result.oracle.canonicalDomDigest}`,
  );
  assert(
    result.oracle.focusStateDigest === ORACLE.focus.toString(16).padStart(8, "0"),
    `JS focusStateDigest ${result.oracle.focusStateDigest}`,
  );
  assert(
    result.oracle.accessibilityStateDigest ===
      ORACLE.accessibility.toString(16).padStart(8, "0"),
    `JS accessibilityStateDigest ${result.oracle.accessibilityStateDigest}`,
  );
  assert(
    result.semanticDigest === ORACLE.semantic.toString(16).padStart(8, "0"),
    `JS semanticDigest ${result.semanticDigest}`,
  );
  assert(
    result.counters.turns === ORACLE.turns,
    `JS turns ${result.counters.turns}`,
  );
  assert(
    result.counters.pathNodesExpanded === ORACLE.pathNodesExpanded,
    `JS pathNodesExpanded ${result.counters.pathNodesExpanded}`,
  );
  assert(
    result.counters.lineOfSightTests === ORACLE.lineOfSightTests,
    `JS lineOfSightTests ${result.counters.lineOfSightTests}`,
  );
  assert(
    result.counters.stateUpdates === ORACLE.stateUpdates,
    `JS stateUpdates ${result.counters.stateUpdates}`,
  );
  assert(
    result.counters.domMutations === ORACLE.domMutations,
    `JS domMutations ${result.counters.domMutations}`,
  );
});

Deno.test("multilang game-tactics-grid: C kernel matches the JS oracle exactly", async () => {
  const fixture = await readFixture();
  const r = runKernel(await loadWasm("tactics_kernel_c.wasm"), fixture);
  assertOracle("C", r);
});

Deno.test("multilang game-tactics-grid: C++ kernel matches the JS oracle exactly", async () => {
  const fixture = await readFixture();
  const r = runKernel(await loadWasm("tactics_kernel_cpp.wasm"), fixture);
  assertOracle("C++", r);
});

Deno.test("multilang game-tactics-grid: Rust kernel matches the JS oracle exactly", async () => {
  const fixture = await readFixture();
  const r = runKernel(await loadWasm("tactics_kernel_rs.wasm"), fixture);
  assertOracle("Rust", r);
});

Deno.test("multilang game-tactics-grid: AssemblyScript kernel matches the JS oracle exactly", async () => {
  const fixture = await readFixture();
  const r = runKernel(
    await loadWasm("tactics_kernel_asc.wasm", { env: { abort: () => {} } }),
    fixture,
  );
  assertOracle("AS", r);
});
