// scripts/build-worker-anchors.ts
//
// Manifest redesign, slice 1 (docs/manifest-redesign.md): worker EXPECTED
// anchors that pin fetched artifact bytes are generated from the bytes, not
// hand-maintained. One generated surface replaces six hardcoded literals.
//
// Scope: file-byte anchors only (sha256 of a public/ artifact). Runtime
// counters/digests and generated-fixture pins stay inline in the workers —
// they pin execution, not bytes, and are covered by contract tests.
//
// Usage:
//   deno run --allow-read --allow-write=public scripts/build-worker-anchors.ts
//   deno run --allow-read scripts/build-worker-anchors.ts --check   (gate: freshness)

import { sha256Hex } from "../lib/canonical.ts";

const ROOT_PATH = new URL("../", import.meta.url).pathname;
const OUT = `${ROOT_PATH}public/worker-anchors.generated.js`;

/** Generated key → worker file (verified to exist + consume the anchors). */
export const WORKERS: Record<string, string> = {
  "pcap-decode": "public/pcap-decode-worker.js",
  "text-gc-document-edit": "public/text-gc-document-edit-worker.js",
  "cad-mesh-repair": "public/benchmarks/cad-mesh-repair-v1/worker.js",
  "game-ecs-frame-update": "public/benchmarks/game-ecs-frame-update/worker.js",
};

/** Generated key → anchor key → artifact file the anchor pins (route path under public/). */
export const ANCHORS: Record<string, Record<string, string>> = {
  "pcap-decode": {
    fixture: "public/artifacts/base-network-pcap-decode/fixture.pcap",
    output: "public/artifacts/base-network-pcap-decode/reference-output.bin",
    wasm: "public/artifacts/base-network-pcap-decode/pcap-decode.wasm",
  },
  "text-gc-document-edit": {
    fixture: "public/artifacts/text-gc-document-edit/fixture.v1.txt",
    fixtureManifest: "public/artifacts/text-gc-document-edit/fixture-manifest.json",
    reference: "public/artifacts/text-gc-document-edit/reference.json",
    buildManifest: "public/artifacts/text-gc-document-edit/build-manifest.json",
    js: "benchmarks/v1/text-gc-document-edit/workload.js",
    wasm: "public/artifacts/text-gc-document-edit/text-gc-document-edit.wasm",
    kotlinGlue: "public/artifacts/text-gc-document-edit/text-gc-document-edit.mjs",
    kotlinImports: "public/artifacts/text-gc-document-edit/text-gc-document-edit.import-object.mjs",
    kotlinBuiltins: "public/artifacts/text-gc-document-edit/text-gc-document-edit.js-builtins.mjs",
  },
  "cad-mesh-repair": {
    fixture: "public/artifacts/cad-mesh-repair-v1/dirty-grid.stl",
    wasm: "public/artifacts/cad-mesh-repair-v1/mesh-repair.wasm",
  },
  "game-ecs-frame-update": {
    wasmSha256: "public/artifacts/game-ecs-frame-update-v1/ecs-frame-update.wasm",
  },
};

async function build(): Promise<string> {
  const blocks: string[] = [];
  for (const key of Object.keys(WORKERS).sort()) {
    const entries: string[] = [];
    for (
      const [anchor, file] of Object.entries(ANCHORS[key]).sort((a, b) => a[0] < b[0] ? -1 : 1)
    ) {
      const bytes = await Deno.readFile(`${ROOT_PATH}${file}`);
      entries.push(`    ${anchor}: "${await sha256Hex(bytes)}",`);
    }
    blocks.push(`  "${key}": Object.freeze({\n${entries.join("\n")}\n  }),`);
  }
  return `// GENERATED by scripts/build-worker-anchors.ts — do not edit by hand.
// Regenerate: deno run --allow-read --allow-write=public scripts/build-worker-anchors.ts
// Source of truth: the artifact bytes on disk (docs/manifest-redesign.md, slice 1).
export const WORKER_ANCHORS = Object.freeze({
${blocks.join("\n")}
});
`;
}

if (import.meta.main) {
  await main();
}

async function main() {
  const next = await build();
  let current = "";
  try {
    current = await Deno.readTextFile(OUT);
  } catch { /* absent */ }

  if (Deno.args.includes("--check")) {
    if (current !== next) {
      console.error(
        `STALE: ${OUT}\nworker anchors drift — regenerate with scripts/build-worker-anchors.ts`,
      );
      Deno.exit(1);
    }
    console.log("worker anchors up to date");
  } else if (current !== next) {
    await Deno.writeTextFile(OUT, next);
    console.log(`wrote ${OUT}`);
  } else {
    console.log("worker anchors unchanged");
  }
}
