// scripts/build-multilang-dart-gc-document.ts
//
// Builds the Dart/WasmGC engine for text.gc-document-edit.v1 and refuses to
// emit it unless it reproduces the pinned oracle exactly.
//
// Why this workload needed a Dart row
// -----------------------------------
// text.gc-document-edit.v1 is the suite's GC-pressure workload: 256 initial
// nodes, then 10,000 edits that allocate 3,334 nodes and drop 3,333 of them.
// It shipped comparing JavaScript against four kernels (C, C++, Rust,
// AssemblyScript) that all hold the document in linear-memory slot arrays and
// never allocate. The one language in the suite with a real managed heap was
// missing from the workload built to stress managed heaps.
//
// Why this is a separate builder
// ------------------------------
// The committed gc_document_kernel_{c,cpp,rs,asc}.wasm artifacts have no
// builder in this repository — nothing under scripts/ compiles them, and
// scripts/build-multilang-wasm-benchmark.ts never mentions them. Rather than
// leave the Dart artifact in the same unbuildable state, this script builds
// it, and does so without touching any other language's committed bytes.
// dart2wasm 3.12.2 reproduces byte-identically, so re-running this on a
// matching SDK is a no-op.
//
// Flags match the Track A Dart rows elsewhere in the suite exactly:
//   dart compile wasm --no-source-maps   (dart2wasm default, -O1)
// This is a Track A engine, not a Track B optimization variant. The -O
// variants live in scripts/build-multilang-dart-opt.ts.
//
// Equivalence: bit-identical. The counters and the FNV-1a canonical digest
// must equal public/artifacts/text-gc-document-edit/reference.json and the
// values the existing kernels produce. No new oracle is defined here.
//
// Toolchain: Dart SDK 3.12.2.
//
// Usage:
//   deno run --allow-all scripts/build-multilang-dart-gc-document.ts

const rootDir = new URL("../", import.meta.url).pathname.replace(/\/$/, "");
const artifactsDir = `${rootDir}/public/artifacts/multilang-wasm-benchmark`;
const source = `${rootDir}/benchmarks/multilang-wasm/text-gc-document-edit/gc_document_kernel.dart`;
const fixturePath = `${rootDir}/public/artifacts/text-gc-document-edit/fixture.v1.txt`;
const outBase = "gc_document_kernel_dart";

/** Pinned oracle — public/artifacts/text-gc-document-edit/reference.json and
 * tests/multilang-gc-document-edit.test.ts. Mirrored, never redefined. */
const ORACLE = Object.freeze({
  inserts: 3334,
  deletes: 3333,
  reparents: 3333,
  finalNodes: 257,
  childInsertions: 6922,
  childRemovals: 6666,
  parentWrites: 10255,
  canonicalFnv: 0x6acfb345,
});

const ORACLE_ORDER = [
  "inserts",
  "deletes",
  "reparents",
  "finalNodes",
  "childInsertions",
  "childRemovals",
  "parentWrites",
  "canonicalFnv",
] as const;

async function run(cmd: string, args: string[], label: string): Promise<void> {
  const { code, stderr } = await new Deno.Command(cmd, {
    args,
    stdout: "piped",
    stderr: "piped",
  }).output();
  if (code !== 0) {
    throw new Error(`${label} failed:\n${new TextDecoder().decode(stderr)}`);
  }
}

async function sha256(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", bytes as BufferSource);
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

interface DartKernels {
  gc_document_edit_trace(
    fixture: Uint8Array,
    len: number,
    out: Uint32Array,
  ): number;
}

console.log(`Compiling ${outBase} with dart compile wasm (default -O1)...`);
await run("dart", [
  "compile",
  "wasm",
  "--no-source-maps",
  source,
  "-o",
  `${artifactsDir}/${outBase}.wasm`,
], `compile ${outBase}`);

// dart2wasm also emits a source map and a support stub; neither is served nor
// referenced by the retained glue, so drop them (same handling as the main
// builder's Dart artifacts).
for (const extra of [`${outBase}.wasm.map`, `${outBase}.support.js`]) {
  try {
    await Deno.remove(`${artifactsDir}/${extra}`);
  } catch {
    // already absent
  }
}

// The generated glue is committed; prefix the generated-file lint header the
// way the main builder does so `deno lint` does not report on generated code.
const gluePath = `${artifactsDir}/${outBase}.mjs`;
const glueText = await Deno.readTextFile(gluePath);
if (!glueText.startsWith("// deno-lint-ignore-file")) {
  await Deno.writeTextFile(
    gluePath,
    `// deno-lint-ignore-file -- generated by dart2wasm (dart compile wasm)\n${glueText}`,
  );
}

// --- Verify against the pinned oracle before the artifact is allowed to ship.

const fixture = await Deno.readFile(fixturePath);
const wasmBytes = await Deno.readFile(`${artifactsDir}/${outBase}.wasm`);

const glue = await import(`file://${gluePath}`);
const app = await glue.compile(wasmBytes);
const inst = await app.instantiate({});
inst.invokeMain();
const kernels = (globalThis as Record<string, unknown>).dartKernels as DartKernels | undefined;
if (!kernels) throw new Error(`dartKernels not published by ${outBase} main()`);

const out = new Uint32Array(8);
const ret = kernels.gc_document_edit_trace(fixture, fixture.byteLength, out);

const got: Record<string, number> = {
  inserts: out[0],
  deletes: out[1],
  reparents: out[2],
  finalNodes: out[3],
  childInsertions: out[4],
  childRemovals: out[5],
  parentWrites: out[6],
  canonicalFnv: out[7] >>> 0,
};

const drift = ORACLE_ORDER.filter((k) => got[k] !== ORACLE[k])
  .map((k) => `${k}: got ${got[k]}, oracle ${ORACLE[k]}`);
if (ret !== ORACLE.finalNodes) drift.push(`return value: got ${ret}, oracle ${ORACLE.finalNodes}`);
if (drift.length > 0) {
  // Leave nothing shippable behind: a kernel that does not reproduce the
  // oracle must not sit in the artifacts directory looking committable.
  for (const f of [`${outBase}.wasm`, `${outBase}.mjs`]) {
    try {
      await Deno.remove(`${artifactsDir}/${f}`);
    } catch { /* already absent */ }
  }
  throw new Error(
    `${outBase} drifted from the pinned oracle and was removed:\n  ${drift.join("\n  ")}`,
  );
}

const glueBytes = await Deno.readFile(gluePath);
console.log(`\n${outBase} reproduces the pinned oracle exactly:`);
for (const k of ORACLE_ORDER) {
  const v = got[k];
  console.log(`  ${k.padEnd(16)} ${k === "canonicalFnv" ? "0x" + v.toString(16) : v}`);
}
console.log(`\n  ${outBase}.wasm  ${wasmBytes.byteLength} B  sha256 ${await sha256(wasmBytes)}`);
console.log(`  ${outBase}.mjs   ${glueBytes.byteLength} B  sha256 ${await sha256(glueBytes)}`);
