import { canonicalize, sha256Hex } from "../lib/canonical.ts";

const root = new URL("../", import.meta.url);
const project = "benchmarks/v1/text-gc-document-edit/kotlin";
const generated = `${project}/build/compileSync/wasmJs/main/productionExecutable/optimized`;
const output = new URL("public/artifacts/text-gc-document-edit/", root);
await Deno.mkdir(output, { recursive: true });

const names = [
  "text-gc-document-edit.mjs",
  "text-gc-document-edit.import-object.mjs",
  "text-gc-document-edit.js-builtins.mjs",
  "text-gc-document-edit.wasm",
];
const outputs = [];
for (const name of names) {
  let bytes = await Deno.readFile(new URL(`${generated}/${name}`, root));
  if (name.endsWith(".mjs")) {
    let text = new TextDecoder().decode(bytes);
    if (name === "text-gc-document-edit.mjs") {
      const original =
        "const path = await import(/* webpackIgnore: true */'https://deno.land/std/path/mod.ts');\n    const binary = Deno.readFileSync(path.fromFileUrl(import.meta.resolve(wasmFilePath)));";
      const replacement =
        "const url = await import(/* webpackIgnore: true */'node:url');\n    const binary = Deno.readFileSync(url.fileURLToPath(import.meta.resolve(wasmFilePath)));";
      if (!text.includes(original)) throw new Error("Kotlin Deno glue patch anchor missing");
      text = text.replace(original, replacement);
      const browserOriginal =
        "wasmInstance = (await WebAssembly.instantiateStreaming(fetch(new URL('./text-gc-document-edit.wasm',import.meta.url).href), importObject, wasmOptions)).instance;";
      const browserReplacement =
        "const pinnedBytes = globalThis.__TEXT_GC_DOCUMENT_EDIT_WASM_BYTES__;\n    if (!(pinnedBytes instanceof Uint8Array)) throw new Error('pinned WasmGC bytes missing');\n    wasmInstance = (await WebAssembly.instantiate(pinnedBytes, importObject, wasmOptions)).instance;";
      if (!text.includes(browserOriginal)) {
        throw new Error("Kotlin browser glue patch anchor missing");
      }
      text = text.replace(browserOriginal, browserReplacement);
    }
    text = `// deno-lint-ignore-file -- generated by Kotlin/Wasm 2.3.21\n${text}`;
    bytes = new TextEncoder().encode(text);
  }
  await Deno.writeFile(new URL(name, output), bytes);
  outputs.push({
    path: `public/artifacts/text-gc-document-edit/${name}`,
    bytes: bytes.length,
    sha256: await sha256Hex(bytes),
  });
}

const sourcePaths = [
  `${project}/settings.gradle.kts`,
  `${project}/build.gradle.kts`,
  `${project}/gradle.properties`,
  `${project}/gradle.lockfile`,
  `${project}/toolchain.lock.json`,
  `${project}/src/wasmJsMain/kotlin/Main.kt`,
  "benchmarks/v1/text-gc-document-edit/workload.js",
  "scripts/build-text-gc-document-edit-fixture.ts",
  "scripts/build-text-gc-document-edit-wasmgc.sh",
  "scripts/finalize-text-gc-document-edit-wasmgc.ts",
  "deno.json",
  "deno.lock",
];
const sources = [];
for (const path of sourcePaths) {
  const bytes = await Deno.readFile(new URL(path, root));
  sources.push({ path, bytes: bytes.length, sha256: await sha256Hex(bytes) });
}
const sourceTree = sources.map(({ path, sha256 }) => `${path}\0${sha256}\n`).join("");
const fixtureManifestBytes = await Deno.readFile(new URL("fixture-manifest.json", output));
const referenceBytes = await Deno.readFile(new URL("reference.json", output));
const wasm = outputs.find((entry) => entry.path.endsWith(".wasm"))!;
const manifest = {
  schemaVersion: 1,
  registrationId: "text.gc-document-edit.v1-supplemental-registration-v1",
  target: "wasmgc-controlled",
  sourceRepository: "https://github.com/PaulKinlan/wasm-vs-js",
  sourceCommit: "candidate commit attested by exact-commit independent review",
  sourceTreeSha256: await sha256Hex(sourceTree),
  frozenCatalog: {
    path: "catalog/workloads.v1.json",
    sha256: "6665664f984683e5b7d3fdc8c1602198124844704c224a526d48be2f02edf9d4",
    immutable: "byte-for-byte",
  },
  toolchain: {
    deno: Deno.version.deno,
    gradle: "9.6.1",
    gradleDistributionSha256: "9c0f7faeeb306cb14e4279a3e084ca6b596894089a0638e68a07c945a32c9e14",
    kotlinPlugin: "2.3.21",
    java: "OpenJDK 26.0.1",
    target: "wasmJs browser production executable",
    command: "scripts/build-text-gc-document-edit-wasmgc.sh",
    generatedGluePatch:
      "replace Deno-only unversioned std/path import with node:url fileURLToPath; browser branch unchanged",
  },
  wasmFeatures: {
    gc: true,
    exceptionHandling: true,
    jsStringBuiltins: true,
    proof:
      "Kotlin/Wasm compiler target plus successful module execution and wasmGcFeatureProof export; validation test rejects missing GC struct/array type forms",
    portableGcDiagnostics: "unavailable",
  },
  fixtureManifest: {
    path: "public/artifacts/text-gc-document-edit/fixture-manifest.json",
    sha256: await sha256Hex(fixtureManifestBytes),
  },
  reference: {
    path: "public/artifacts/text-gc-document-edit/reference.json",
    sha256: await sha256Hex(referenceBytes),
  },
  outputs,
  sources,
  artifact: { path: wasm.path, sha256: wasm.sha256, bytes: wasm.bytes },
};
await Deno.writeTextFile(new URL("build-manifest.json", output), `${canonicalize(manifest)}\n`);
console.log(`text.gc-document-edit WasmGC ${wasm.bytes} bytes ${wasm.sha256}`);
