// rebind-regex-log-scan-identity.ts — regenerates the benchmarks
// text.regex-log-scan identity pins from the CURRENT served files.
// The demos identity is rebuilt by build-text-regex-log-scan.ts; the
// benchmarks worker imports ITS OWN identity.js (benchmarks/...), which the
// rebind must keep in sync or the playground card fails with
// "served raw-byte hash mismatch: registration".
import { sha256Hex } from "../lib/canonical.ts";

const root = new URL("../", import.meta.url);

const files: Array<[string, string]> = [
  ["registration", "public/data/base-implementations/text.regex-log-scan.v1.json"],
  ["buildManifest", "public/artifacts/text-regex-log-scan/build-manifest.json"],
  ["inputManifest", "public/artifacts/text-regex-log-scan/input-manifest.json"],
  ["outputManifest", "public/artifacts/text-regex-log-scan/output-manifest.json"],
  ["wasm", "public/artifacts/text-regex-log-scan/text-regex-log-scan.wasm"],
  ["captures", "public/artifacts/text-regex-log-scan/ordered-captures.bin"],
  ["inputModule", "benchmarks/text-regex-log-scan/input.js"],
  ["workloadModule", "benchmarks/text-regex-log-scan/workload.js"],
  ["workerModule", "public/benchmarks/base/text.regex-log-scan.v1/worker.js"],
];

const registration = JSON.parse(
  await Deno.readTextFile(new URL("benchmarks/text-regex-log-scan/registration.json", root)),
);
const sourceCommit = (await Deno.readTextFile(
  new URL("artifacts/base/text-regex-log-scan/source-commit.txt", root),
)).trim();

const rawSha256: Record<string, string> = {};
for (const [name, path] of files) {
  rawSha256[name] = await sha256Hex(await Deno.readFile(new URL(path, root)));
}

const identityText =
  `// Generated by scripts/build-text-regex-log-scan.ts; source commit is the trust root.\nexport const IDENTITY = {\n  "workloadId": ${
    JSON.stringify(registration.catalogEntryId)
  },\n  "sourceCommit": ${JSON.stringify(sourceCommit)},\n  "rawSha256": {\n${
    Object.entries(rawSha256)
      .map(([name, value]) => `    ${JSON.stringify(name)}: ${JSON.stringify(value)},`)
      .join("\n")
  }\n  },\n};\n`;

await Deno.writeTextFile(
  new URL("public/benchmarks/base/text.regex-log-scan.v1/identity.js", root),
  identityText,
);
console.log(
  `rebind regex-log-scan identity: registration ${
    rawSha256.registration.slice(0, 12)
  }… workerModule ${rawSha256.workerModule.slice(0, 12)}…`,
);
